INSERT INTO talk VALUES (NULL, 'Writing Fast Tests Against Enterprise Rails', 60);
INSERT INTO talk VALUES (NULL, 'Overdoing it in Python', 45);
INSERT INTO talk VALUES (NULL, 'Lua for the Masses', 30);
INSERT INTO talk VALUES (NULL, 'Ruby Errors from Mismatched Gem Versions', 45);
INSERT INTO talk VALUES (NULL, 'Common Ruby Errors', 45);
INSERT INTO talk VALUES (NULL, 'Rails for Python Developers', 5);
INSERT INTO talk VALUES (NULL, 'Communicating Over Distance', 60);
INSERT INTO talk VALUES (NULL, 'Accounting-Driven Development', 45);
INSERT INTO talk VALUES (NULL, 'Woah', 30);
INSERT INTO talk VALUES (NULL, 'Sit Down and Write', 30);
INSERT INTO talk VALUES (NULL, 'Pair Programming vs Noise', 45);
INSERT INTO talk VALUES (NULL, 'Rails Magic', 60);
INSERT INTO talk VALUES (NULL, 'Ruby on Rails: Why We Should Move On', 60);
INSERT INTO talk VALUES (NULL, 'Clojure Ate Scala (on my project)', 45);
INSERT INTO talk VALUES (NULL, 'Programming in the Boondocks of Seattle', 30);
INSERT INTO talk VALUES (NULL, 'Ruby vs. Clojure for Back-End Development', 30);
INSERT INTO talk VALUES (NULL, 'Ruby on Rails Legacy App Maintenance', 60);
INSERT INTO talk VALUES (NULL, 'A World Without HackerNews', 30);
INSERT INTO talk VALUES (NULL, 'User Interface CSS in Rails Apps', 30);
